version: "3"
services:
  reverseproxy:
    build:
      context: .
    image: smaillns/nginx-reverse-proxy
  backend_user:
    build:
      context: ../../udacity-restapi-user
    image: smaillns/udacity-restapi-user
  backend_feed:
    build:
      context: ../../udacity-restapi-feed  
    image: smaillns/udacity-restapi-feed
  frontend:
    build:
      context: ../../udacity-frontend  
    image: smaillns/udacity-frontend
