apiVersion: v1
kind: Service
metadata:
  labels:
    service: backend-feed
  name: backend-feed
spec:
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    service: backend-feed