apiVersion: v1
kind: Service
metadata:
  labels:
    service: reverseproxy
  name: reverseproxy
spec:
  ports:
  - name: "8088"
    port: 8088
    targetPort: 8088
  selector:
    service: reverseproxy
#  type: LoadBalancer    
